workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: meplusapp
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
      - xcode-project use-profiles
      - xcode-project build-ipa \
          --workspace ios/Runner.xcworkspace \
          --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
