workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS Release (No Code Sign)
        script: |
          flutter build ios --release --no-codesign
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../Runner-unsigned.ipa Payload/
          cd ../../..
          ls -lh Runner-unsigned.ipa
    artifacts:
      - Runner-unsigned.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - fadihamad40984@gmail.com
        notify:
          success: true
          failure: true


