workflows:
  ios-release:
    name: iOS Release (Personal Account)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: meplusapp

    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build Flutter iOS (Release, no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Build signed IPA (App Store)
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        issuer_id: bc99df75-7e2d-4458-902e-470d647f425a
        key_id: 68Y9MFMUVZ
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY